# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'HeroTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeroTest
  pod 'Hero'
  pod 'Charts'

  target 'HeroTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HeroTestUITests' do
    # Pods for testing
  end

end
